#ifndef TAG_VTKIGNSEVENTS_H
#define TAG_VTKIGNSEVENTS_H

enum VTK_IGNS_EVENTS
{
    IGNS_MOVE_2D_POINT = 1,
    IGNS_MOVE_3D_POINT,                   
    IGNS_HIGHLIGHT_POINT,
    IGNS_PLANE_SELECTED,
    IGNS_SAVE_POINTER_POSITION,
    IGNS_SAVE_MOUSE_POSITION
};

#endif //TAG_VTKIGNSEVENTS_H

